/**
 * config.example.js
 * Template for runtime environment variables.
 * Copy this file to config.js and inject real keys.
 */
window.ENV = {
  GEMINI_API_KEY:      "YOUR_GEMINI_API_KEY",
  FIREBASE_API_KEY:    "YOUR_FIREBASE_API_KEY",
  FIREBASE_AUTH_DOMAIN:"YOUR_FIREBASE_AUTH_DOMAIN",
  FIREBASE_PROJECT_ID: "YOUR_FIREBASE_PROJECT_ID",
  FIREBASE_STORAGE:    "YOUR_FIREBASE_STORAGE",
  FIREBASE_SENDER_ID:  "YOUR_FIREBASE_SENDER_ID",
  FIREBASE_APP_ID:     "YOUR_FIREBASE_APP_ID",
  FIREBASE_MEASUREMENT:"YOUR_FIREBASE_MEASUREMENT",
  FIREBASE_DB_URL:     "YOUR_FIREBASE_DB_URL",
  MAPS_API_KEY:        "YOUR_MAPS_API_KEY",
  ROUTES_API_KEY:      "YOUR_ROUTES_API_KEY",
};
